In [2]:
import numpy as np
import tensorflow as tf

In this module we are going to cover some of the most fundamental conept of tensors using tensorflow.

More specificially, we're going to cover :
* Introduction to tensors 
* Getting information from tensors 
* Manipulating Tensors
* Tensors and NumPy
* Using @tf.function(a wau to speed up your regular python functions)
* Using GPUs with TensorFlow(or TPUs)
* Exercises to try for yourself

### Introduction to Tensors

In [3]:
# Import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.5.0


In [4]:
# Create tensors with tf.constant()
scaler = tf.constant(7)
scaler

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [5]:
 # check the number of dimensions of a tensor(ndim stands for number of dimensions)
scaler.ndim

0

In [6]:
# create a vector 
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10])>

In [7]:
# check the dimension of our vector
vector.ndim

1

In [8]:
# create a matrix (has more than one dimension)
matrix = tf.constant([[10,7],
                     [7,10]])

In [9]:
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]])>

In [10]:
matrix.ndim

2

In [11]:
# Create another matrix 
another_matrix = tf.constant([[10., 7.],
                              [7., 9.],
                              [3.,5.]], dtype= tf.float16) #specify the data type with dtype parameter

In [12]:
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 7.,  9.],
       [ 3.,  5.]], dtype=float16)>

In [13]:
# what's the number of dimensions of another_matrix?
another_matrix.ndim

2

In [14]:
# Let's create a tensor 
tensor = tf.constant([[[1, 2, 3],
                       [4, 5, 6]],
                      [[7, 8, 9 ],
                       [10, 11, 12]],
                      [[13, 14, 15],
                       [16, 17, 18]]])

In [15]:
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])>

In [16]:
tensor.ndim

3

what we've created so far:

* Scalar: a single number
* Vector: a number with direction (e.g. wind speed and direction)
* Mateix: a 2-dimensional array of numbers
* tensor: an n-dimensional array of numbers(when n can be any number, a 0-dimensional tensor is a scaler, a 1-dimensional tensor is a vector)

###  Creating tensors with `tf.Variable`

In [17]:
# Create the same tensor with tf.variable() as above
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7])>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7])>)

In [18]:
# Let's try change one of the element in our changeable tensor
changeable_tensor[0] = 7

TypeError: 'ResourceVariable' object does not support item assignment

In [19]:
# How about we try .assign()
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7])>

**Note:** Rarely in practice will you need to decide whether to use `tf.constant` or `tf.varible` to create tensors, as TensorFlow does this for you. However, If in doubt, use `tf.constant` and change it later if needed.

###  Creating Random tensors

Random tensors are tensors of some arbitary size which contain some random numbers.

In [20]:
# create two random (but the same ) tensors
random_1 = tf.random.Generator.from_seed(42) # set seed for reproducibility
random_1 = random_1.normal(shape=(3,2))
random_1
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape = (3, 2))
random_2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193765, -1.8107855 ]], dtype=float32)>

In [21]:
# Are they equal?
random_1 == random_2

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True],
       [ True,  True]])>

### Shuffle the order of elements in a tensor

In [22]:
# shuffle a tensor (valuable for when you want to shuffle your data so the inherent order doesn't effect learning)
not_shuffled = tf.constant([[10, 7],
                            [3, 5],
                            [6, 8]])
not_shuffled.ndim

2

> It looks like if we want our shuffled tensors to be in the same order, we've got to use the global level random seed as well as operational level random seed

In [23]:
# Shuffle our not shuffled tensor
tf.random.set_seed(42) # Global level ranodm seed
shuffled = tf.random.shuffle(not_shuffled, seed = 42) #operational level random  seed 
shuffled 

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  5],
       [ 6,  8]])>

### Other ways to make tensors

In [24]:
#create a tensor of all ones
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [25]:
# Create a tensors of all zeros 
tf.zeros(shape = (3,4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

### Turn NumPy arrays into tensors 

The main difference between NumPy arrays and TensorFlow tensors is that tensors can be run on a GPU(much faster for numerical computing).

In [26]:
# You can also turn NumPy arrays into tensors 
import numpy as np
numpy_a = np.arange(1, 25, dtype =np.int32 )

In [27]:
numpy_a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [28]:
A = tf.constant(numpy_a, shape=(2,3,4)) 

In [29]:
A

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])>

### Getting information from tensors 

when dealing with tensors you probably want to be aware of the following attributes:
* Shape
* Rank
* Axis or Dimensions
* Size

In [30]:
# Create a rank 4 tensor( 4 dimensions )
rank_4_tensor = tf.zeros(shape = [2, 3, 4, 5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [31]:
 rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [32]:
 # Get various attributes of our tensor
print('Datatype of every elements:', rank_4_tensor.dtype)
print('Number of dimensions (rank):', rank_4_tensor.ndim)
print('Shape of the tensor:', rank_4_tensor.shape)
print('Elements along the 0 axis:', rank_4_tensor.shape[0])
print('Elements along the last axis:', rank_4_tensor.shape[-1])
print('Total number of elements in our tensor:', tf.size(rank_4_tensor))
print('Total number of elements in our tensor:', tf.size(rank_4_tensor).numpy())

Datatype of every elements: <dtype: 'float32'>
Number of dimensions (rank): 4
Shape of the tensor: (2, 3, 4, 5)
Elements along the 0 axis: 2
Elements along the last axis: 5
Total number of elements in our tensor: tf.Tensor(120, shape=(), dtype=int32)
Total number of elements in our tensor: 120


### Indexing tensors 

Tensor can be indexed just like python lists.


In [33]:
some_list = [1, 2, 3, 4]
some_list[:2]

[1, 2]

In [34]:
# Get the first two elements of each dimensions
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [35]:
# Get the first element from each dimension from each index for the final one
rank_4_tensor[:1, :1, :1]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [36]:
rank_4_tensor[:1, :1, :, :1]

<tf.Tensor: shape=(1, 1, 4, 1), dtype=float32, numpy=
array([[[[0.],
         [0.],
         [0.],
         [0.]]]], dtype=float32)>

In [37]:
# Create a rank 2 tensor(2 dimensions)
rank_2_tensor = tf.constant([[10, 7],
                            [5, 6]])

In [38]:
rank_2_tensor.shape, rank_2_tensor.ndim

(TensorShape([2, 2]), 2)

In [39]:
 # Get the last item of each of our rank 2 tensor 
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 6])>

In [40]:
# Add in extra dimension to our rank 2 tensor
rank_3_tensor = rank_2_tensor[...,tf.newaxis] #[:, :, tf.newaxis]

In [41]:
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 5],
        [ 6]]])>

In [42]:
# Alterenative to tf.newaxis
tf.expand_dims(rank_2_tensor, axis = -1) # '-1' means expand the final axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 5],
        [ 6]]])>

In [43]:
tf.expand_dims(rank_2_tensor, axis = 0) #expand the 0-axis

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 5,  6]]])>

###  Manipulating Tensors(tensor operations)

**Basic Opeartion**

`+`,`-`,`*`,`/`

In [44]:
# You can add values to a tensor using the addition operator
tensor = tf.constant([[10, 7], 
                      [3, 4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]])>

In [45]:
#Original tensor is unchanged
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]])>

In [46]:
# Multiplication also works 
tensor * 9

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[90, 63],
       [27, 36]])>

In [47]:
# Substraction if you want 
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]])>

In [48]:
# we can use nbuilt tensorflow function too
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]])>

#### Matrix Multiplicatoin

In machine learning, matric multiplication is one of the most common tensor operations.

In [49]:
# Matrix multiplication in tensorflow
print(tensor)
tf.matmul(tensor, tensor)

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]])>

In [50]:
tensor * tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  49],
       [  9,  16]])>

In [51]:
tns1 = tf.constant([[1,2,5],
                    [7,2,1],
                    [3,3,3]])
tns2 = tf.constant([[20,59],
                    [34,57],
                    [30, 60]])
mul = tf.matmul(tns1, tns2)

In [52]:
mul

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[238, 473],
       [238, 587],
       [252, 528]])>

In [53]:
# Matrix multiplication with Python operator "@"
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]])>

There are two rules our tensors (or matrices) need to fulfil if we're going to matrix multiply them:

1. The inner dimensions must match
2. The resulting matrix has the shape of the outer dimesnions

In [54]:
# create a tensor (3,3)
tns1 = tf.constant([[1,2],
                    [7,2],
                    [3,3]])
# Create a tensor (3, 2)
tns2 = tf.constant([[20,59],
                    [34,57],
                    [30, 60]])

tns2 = tf.reshape(tns2, shape=(2,3))

# try to multiply tesnors of same shape
mul = tf.matmul(tns1, tns2)
mul

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[134, 119, 154],
       [254, 473, 358],
       [231, 267, 282]])>

In [55]:
tns1 @ tns2

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[134, 119, 154],
       [254, 473, 358],
       [231, 267, 282]])>

In [56]:
 # Can do the same with transpose
print(tns1)
print('Transpose of tns1 is:', tf.transpose(tns1))
print('But reshape  of the tns1 is:',tf.reshape(tns1 , shape=(2,3)))

tf.Tensor(
[[1 2]
 [7 2]
 [3 3]], shape=(3, 2), dtype=int32)
Transpose of tns1 is: tf.Tensor(
[[1 7 3]
 [2 2 3]], shape=(2, 3), dtype=int32)
But reshape  of the tns1 is: tf.Tensor(
[[1 2 7]
 [2 3 3]], shape=(2, 3), dtype=int32)


**The dot product**

Matrix Multiplication is also referref to as dot product.

You can also perform matrix multiplication using:

* `tf.matmul()`
* `tf.tensordot()`

In [59]:
# Let's try multiplication with tf.tensordot() one's with tansposed tns2 and second wiht reshaped tns2
mul = tf.tensordot(tns1, tf.transpose(tns1), axes =1)
mul


<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 5, 11,  9],
       [11, 53, 27],
       [ 9, 27, 18]])>

In [61]:
mul = tf.tensordot(tns1, tf.reshape(tns2, shape= (2,3)), axes=1 )
mul

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[134, 119, 154],
       [254, 473, 358],
       [231, 267, 282]])>

### Changing the datatype of a tensor

In [63]:
# Create a new tensor with default dataype (float32)
B = tf.constant([[1.7, 8.4]])
B.dtype

tf.float32

In [64]:
C = tf.constant([1,7])
C.dtype

tf.int32

In [69]:
# Change the float32 to float16 (reduced precision)
D = tf.cast(B, dtype= tf.float16)

In [71]:
D.dtype

tf.float16

>Reducing the precision for tensor of million elements  from float32 to float16, we bascially half the size of storing space, allowing hardware acclerators to make calculation on it probably twice as fast. 

### Aggregating Tensor

Aggregating tensors = condecing them from multiple values down to a smaller amount of values.

In [72]:
# Get the absolute value
D = tf.constant([-7, -10])

In [73]:
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10])>

 Let's go through the following forms of aggregation:
* Get the minimum
* Get the Maximum
* Get the mean of the tensor 
* Get the sum of a tensor

In [79]:
# creating a random tensor with values between 0 and 100 of size 50
E = tf.constant(np.random.randint(1,100, size = 50))
E

<tf.Tensor: shape=(50,), dtype=int32, numpy=
array([ 2, 27, 26, 99, 21, 32, 37, 38, 24,  5, 13, 10, 23, 96, 45,  2, 25,
       40, 29, 29, 63, 64, 82, 83, 28, 32, 12, 34, 70, 85, 48, 68, 80, 23,
       89, 17, 76, 72, 79, 35, 76, 71, 25, 53, 24, 75, 20, 35, 47, 58])>

In [80]:
tf.size(E), E.shape, E.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [81]:
# Find the Minimum 
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [82]:
# Find the maximum
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int32, numpy=99>

In [84]:
# Find the mean
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int32, numpy=44>

In [85]:
# Find the sum
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int32, numpy=2247>

In [93]:
# Find the variance
tf.math.reduce_variance(tf.cast(E, dtype= tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=722.2564>

In [95]:
# Find the standard deviation
tf.math.reduce_std(tf.cast(E, dtype=tf.float32)) 

<tf.Tensor: shape=(), dtype=float32, numpy=26.874828>

### FInd the positional maximum and minimum

At which index of the tensor does the maximum or minimum value occurs.

In [96]:
# Create a new tensor for finding positional minimum and maximum
tf.random.set_seed(42)
F = tf.random.uniform (shape = [50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [98]:
# Find the positional maximum
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [105]:
# Find the maximum using positional maximum index
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [106]:
# Find the max value of F
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [107]:
# Find the min value of F
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

###  Squeezing a tensor (removing all single dimensions)

In [112]:
# Create a tensor to get started 
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=[50]) , shape = (1, 1, 1, 1, 50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [113]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [116]:
G_squeezed = tf.squeeze(G)
G_squeezed, G_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>,
 TensorShape([50]))

### One-hot encoding 

In [120]:
# Create a list of indices
some_list = [0, 1, 2, 3] #could be red, green, blue and yellew

# One hot encode our list of indices 
tf.one_hot(some_list, depth = 4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [121]:
# Specify custom vallues of one hot encoding
tf.one_hot( some_list, depth = 4, on_value='i love deep learning', off_value='i also like machine learning')

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'i love deep learning', b'i also like machine learning',
        b'i also like machine learning', b'i also like machine learning'],
       [b'i also like machine learning', b'i love deep learning',
        b'i also like machine learning', b'i also like machine learning'],
       [b'i also like machine learning', b'i also like machine learning',
        b'i love deep learning', b'i also like machine learning'],
       [b'i also like machine learning', b'i also like machine learning',
        b'i also like machine learning', b'i love deep learning']],
      dtype=object)>

### Squaring, log, square root

In [124]:
# Create a tensor
H = tf.range(1,10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [125]:
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])>

In [128]:
# Find the square root
tf.sqrt(tf.cast(H, dtype= tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.2360678, 2.4494896,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [131]:
# Find the log
tf.math.log(tf.cast(H, dtype = tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

### Tensors and NumPy

TensorFlow interacts beautifully with NumPy array

In [133]:
J = tf.constant(np.array([3., 7., 10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [135]:
# Convert our tensor back to numpy array
np.array(J) , type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [136]:
J = tf.constant([3.])
J.numpy()[0]

3.0

## Finding access to GPUs

In [139]:
tf.config.list_physical_devices("GPU")

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [142]:
!nvidia-smi

Mon Oct 11 22:50:03 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 472.12       Driver Version: 472.12       CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ... WDDM  | 00000000:01:00.0 Off |                  N/A |
| N/A   47C    P8     5W /  N/A |   2452MiB /  4096MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

**Note:**If you have access to a CUDA-enabled GPU, tensorflow will automatically use it whenever possible.